os: linux
language: node_js
node_js:
  - 12
cache: npm

notifications:
  email: false

install:
  - npm ci

script:
  - npm run build

deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app: isa-pharmacy-team18-frontend
  on:
    branch: master


